Mioca/Mioca/Areas/Admin/Models/BlogViewModel.cs
using Microsoft.AspNetCore.Http;
using Repository.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mioca.Areas.Admin.Models
{
    public class BlogViewModel
    {
        public int Id { get; set; }
        public bool Status { get; set; }
        public DateTime AddedDate  { get; set; }
        [Required (ErrorMessage ="Ad vacibdir")]
        public string Title { get; set; }
        public string Image { get; set; }
        [Required(ErrorMessage = "Boş olmamalıdır")]
        public IFormFile ImageFile { get; set; }
        [Required(ErrorMessage = "Boş olmamalıdır")]
        public string TextTopQuote { get; set; }
        [Required(ErrorMessage = "Boş olmamalıdır")]
        public string TextBottomQuote { get; set; }
        [Required(ErrorMessage = "Boş olmamalıdır")]
        public string SloganUser { get; set; }
        public int CategoryId { get; set; }
        public List<BlogCategory> Category { get; set; }
        public int[] TagIds { get; set; }
        public string UserId { get; set; }
        public User User { get; set; }
        public List<TagToBlog> TagToBlogs { get; set; }

    }

}

Mioca/Mioca/Areas/Admin/Controllers/BlogController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mioca.Areas.Admin.Models;
using Mioca.Models;
using Repository.Constants;
using Repository.Data;
using Repository.Extensions;
using Repository.Models;
using Repository.Repositories.AdminRepositories;
using Repository.Utils;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Mioca.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BlogController : Controller
    {
        private readonly IBlogRepository _blog;
        private readonly MiocaDbContext _context;
        private readonly IMapper _mapper;
        private readonly UserManager<User> _usermanager;


        public BlogController(IBlogRepository blog,
                              IMapper mapper,
                              MiocaDbContext context,
                              UserManager<User> usermanager)
        {
            _blog = blog;
            _mapper = mapper;
            _context = context;
            _usermanager = usermanager;
        }


        public IActionResult Blog()
        {
            var blog = _blog.GetBlog();
            var model = _mapper.Map<IEnumerable<Blog>, IEnumerable<BlogGetViewModel>>(blog);
            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var blog = _blog.GetBlogById(id);

            if (blog == null) return NotFound();

            return View(blog);
        }

        [HttpGet]
        public async Task<IActionResult> CreateBlog()
        {
            BlogViewModel model = new BlogViewModel
            {

                Category= await _context.BlogCategorys.ToListAsync(),
               
               
            };

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateBlog(BlogViewModel model)
        {

            model.Category = await _context.BlogCategorys.ToListAsync();
            model.UserId = _usermanager.GetUserId(User);

            if (!ModelState.IsValid) return View(model);



            //category
            var categ = await _context.BlogCategorys.FindAsync(model.CategoryId);
            if (categ == null)
            {
                ModelState.AddModelError(nameof(BlogViewModel.CategoryId), "Choose a valid category");
                return View(model);
            }

         
            if (!model.ImageFile.IsOkay())
            {
                ModelState.AddModelError(nameof(BlogViewModel.ImageFile), "There is a problem in your file");
                return View(model);
            }


            Blog blog = new Blog
            {
                Status = model.Status,
               Title=model.Title,
               TextBottomQuote=model.TextBottomQuote,
               TextTopQuote=model.TextTopQuote,
               SloganUser=model.SloganUser,
                Image = FileUtils.Create(FileConstants.ImagePath, model.ImageFile),
                Category = categ,
                UserId = _usermanager.GetUserId(User),
               
                AddedDate = DateTime.Now,
            };

            await _context.Blogs.AddAsync(blog);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Blog));



        }



        public async Task<IActionResult> UpdateBlog(int id)
        {
            var blog = _blog.GetBlogById(id);


            if (blog == null) return NotFound();

            BlogViewModel model = new BlogViewModel
            {
                CategoryId = blog.CategoryId,
               Title= blog.Title,
                TextTopQuote = blog.TextTopQuote,
                TextBottomQuote=blog.TextBottomQuote,
                Status = blog.Status,
                SloganUser = blog.SloganUser,
                AddedDate = DateTime.Now,
                Category = await _context.BlogCategorys.ToListAsync(),  
                Image = blog.Image,
               
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateBlog(int id, BlogViewModel model)
        {
            var blog = _blog.GetBlogById(id);
            if (blog == null) return NotFound();

            model.Category = await _context.BlogCategorys.ToListAsync();
            if (!ModelState.IsValid) return View(model);



            //category
            var categ = await _context.BlogCategorys.FindAsync(model.CategoryId);
            if (categ == null)
            {
                ModelState.AddModelError(nameof(BlogViewModel.CategoryId), "Choose a valid category");
                return View(model);
            }
           

            if (model.ImageFile != null)
            {
                if (!model.ImageFile.IsOkay())
                {
                    ModelState.AddModelError(nameof(BlogViewModel.ImageFile), "There is a problem in your file");
                    return View(model);
                }
                FileUtils.Delete(Path.Combine(FileConstants.ImagePath, blog.Image));
            }

          
            blog.Title = model.Title;
            blog.TextBottomQuote = model.TextBottomQuote;
            blog.TextTopQuote = model.TextTopQuote;
            blog.SloganUser = model.SloganUser;
            blog.Category = categ;
            blog.Image = model.ImageFile != null ? FileUtils.Create(FileConstants.ImagePath, model.ImageFile) : blog.Image;


            _context.Blogs.Update(blog);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Blog));
        }


        public async Task<IActionResult> Delete(int id)
        {
            var blog = _blog.GetBlogById(id);
            if (blog == null) return NotFound();


            FileUtils.Delete(blog.Image);

            _context.Blogs.Remove(blog);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Blog));

        }


    }
}

Mioca/Mioca/Controllers/BlogController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mioca.Models;
using Repository.Data;
using Repository.Enums;
using Repository.Models;
using Repository.Repositories.ContentRepositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mioca.Controllers
{
    public class BlogController : BaseController
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly MiocaDbContext _context;
        private readonly IContentRepository _content;
        private readonly IMapper _mapper;

        public BlogController(UserManager<User> userManager, 
                              SignInManager<User> signInManager, 
                              RoleManager<IdentityRole> roleManager, 
                              MiocaDbContext context,
                              IContentRepository content,
                              IMapper mapper)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _context = context;
            _content = content;
            _mapper = mapper;
        }

        public IActionResult Index(int? id, int? tagId, int? year, int? month, BlogVm blogfilter, string searchData, int page = 1)
        {
            var setting = _content.GetSetting();
            var userId = _userManager.GetUserId(User);
            decimal pageItemCount = 6;
            ViewBag.UserId = userId;

            ViewBag.categoryId = id;
            IList<Blog> blogs = _context.Blogs.Include(u => u.User)
                                              .Where(b => (id != null ? b.CategoryId == id : true) &&
                                               (tagId != null ? b.TagToBlogs.Any(t => t.TagId == tagId) : true) &&
                                               (year != null ? b.AddedDate.Year == year : true) &&
                                               (month != null ? b.AddedDate.Month == month : true) &&
                                               (b.Status ))
                                               .Where(sr =>
                                               ((searchData != null ? sr.Title.Contains(searchData) : true) || 
                                               (searchData != null ? sr.Category.Name.Contains(searchData) : true)) &&
                                               (blogfilter.catId != null ? sr.CategoryId == blogfilter.catId : true))
                                                     .ToList();


            decimal b = Math.Ceiling(blogs.Count / pageItemCount);
            ViewBag.PageCount = Convert.ToInt32(b);
            ViewBag.ActivePage = page;
            ViewBag.prewPage = page - 1;
            ViewBag.nextPage = page + 1;

            List<Blog> blog = blogs.OrderBy(p => p.Id)
                                       .OrderByDescending(added => added.AddedDate)
                                        .Skip((page - 1) * (int)pageItemCount)
                                        .Take((int)pageItemCount)
                                        .ToList();
            BlogVm model = new BlogVm()
            {
                
                
                Categories = _context.BlogCategorys.Include(b => b.Blogs)
                                                   .Where(bb => bb.Blogs
                                                   .Any(s => s.Status))
                                                   .ToList(),
                Comments = _context.BlogComments.ToList(),

                Setting = _content.Getset(),

            };

            return View(model);
        }



        public IActionResult Details(int Id)
        {
           
            var UserId = _userManager.GetUserId(User);
            Blog blog = _context.Blogs.Include(c => c.User)          
                 .Include(b => b.Comments)
                .ThenInclude(c => c.User)
                .Include(b => b.TagToBlogs)
                 .ThenInclude(c => c.Tag)
                  .Include(b => b.Category)
                 
                 .FirstOrDefault(b => b.Id == Id);


            if (blog == null) return NotFound();
            BlogCommentViewModel model = new BlogCommentViewModel
            {
                Blog = blog,
                Setting = _content.Getset(),
                Categories = _context.BlogCategorys.Include(b => b.Blogs).ToList(),
                Blogs = _context.Blogs.OrderByDescending(b => b.AddedDate).Take(4).ToList()
            };



            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> AddComment(int Id, BlogCommentViewModel model)
        {
            var blog = await _context.Blogs.Include(c => c.User)
                .Include(c => c.Comments)
                .ThenInclude(c => c.User)

                 .FirstOrDefaultAsync(c => c.Id == Id);
            if (blog == null) return NotFound();


            if (!ModelState.IsValid)
            {
                model.Blog = blog;
                return View();
            }
            BlogComment comment = new BlogComment
            {
                Subject = model.Review.Subject,
               Mesage= model.Review.Mesage,
                UserId = _userManager.GetUserId(User),
                BlogId = Id,
                

            };

            await _context.BlogComments.AddAsync(comment);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Details), new { Id });
        }
    }


}

Mioca/Mioca/Views/Blog/Details.cshtml
@model BlogCommentViewModel
@inject SignInManager<User> SignInManager
@{
    ViewData["Title"] = "Blog Details";
}

<main>
    <!--Breadcrumb section start-->
    <section class="breadcrumb-section">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-12 text-center">
                    <h1 class="page-name ">@Model.Blog.Title.Substring(0,20)...</h1>
                    <nav class="d-flex justify-content-center" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-controller="blog" asp-action="index">Blog</a></li>
                            <li class="breadcrumb-item active" aria-current="page">@Model.Blog.Title.Substring(0,20)...</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!--Breadcrumb section end-->
    <!--Blog details section start-->
    <section class="section-style-one">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 col-lg-8 col-md-12 ">
                    <div class="blog-post">
                        <div class="blog-post-image">
                            <img class="img-fluid h-auto" src="~/Uploads/@Model.Blog.Image" alt="blog">
                        </div>
                        <div class="blog-content martop-30">
                            <div class="blog-athor-date">
                                <span> By,<a class="blog-author" href="#"> @Model.Blog.User.Name @Model.Blog.User.Surname</a></span>
                                <span class="blog-date">@Model.Blog.AddedDate.Date.ToString("dd MMMM yyyy")</span>
                            </div>
                            <h4 class="blog-title">
                               @Model.Blog.Title
                            </h4>
                           
                            @Html.Raw(Model.Blog.TextTopQuote)
                        </div>
                        <div class="blog-quate-block">
                            <div class="quate-area">

                                <p class="quate-speech">
                                   @Model.Blog.SloganUser
                                </p>
                                <img class="h-100 speecker-img" src="~/uploads/@Model.Blog.User.Image" alt="" >
                            </div>

                            @Html.Raw(Model.Blog.TextBottomQuote)
                        </div>
                    </div>
                    <div class="tags-social-area d-md-flex justify-content-between">
                        <div class="tags d-flex">
                            <span class="title"><i class="fa fa-tags"></i></span>
                            <ul class="tag-list">
                                @foreach (var tags in Model.Blog.TagToBlogs)
                                {
                                    
                                        <li><a class="tag" href="#">@tags.Tag.Name</a></li>
                                       
                                    

                                }

                              
                            </ul>
                        </div>
                        <div class="socials mb-xs-15 d-flex">
                            <ul class="social">
                                @if (Model.Blog.Socials != null)
                                {
                                    @foreach (var item in Model.Blog.Socials)
                                    {
                                        <li class="m-0">
                                            <a href="@item.Link">@Html.Raw(item.Social.Icon)</a>
                                        </li>
                                    }
                                }

                              
                            </ul>
                        </div>
                    </div>
                    <div class="coment-form-area">
                        <div class="comments">
                            <h2 class="comment-heading">Comments (@Model.Blog.Comments.Count())</h2>
                            <div class="review-wrapper">
                                @foreach (var review in Model.Blog.Comments)
                                {
                                    <div class="review-card">
                                        <div class="user-img">
                                            <img src="~/Uploads/@review.User.Image" alt="">
                                        </div>
                                        <div class="review-content">
                                            <div class="review-user-details">
                                                <div class="d-flex">
                                                    <div class="user-name-data">
                                                        <h4 class="name">@review.User.UserName @review.User.Surname </h4>
                                                        <span class="date">@review.AddedDate.ToString("dd MMMM yyyy")</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="user-comment">
                                                <p>
                                                    @review.Mesage
                                                </p>
                                                <div class="reply">
                                                    <a asp-controller="blog" asp-action="AddComment" asp-route-id="@Model.Blog.Id"><i class="fa fa-reply-all"></i> Reply</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                }

                             
                            </div>
                        </div>

                        @if (SignInManager.IsSignedIn(User))
                        {
                            
                    <div class="comment-form">
                        <h2 class="comment-heading">Leave a Comment</h2>
                        <form asp-controller="Blog" asp-action="AddComment" asp-route-id="@Model.Blog.Id" method="post">
                            <div class="form-inner">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-card  m-0">
                                            <input asp-for="Review.Subject" placeholder="Rəyiniz">
                                            <span class="text-danger" asp-validation-for="Review.Subject"></span>
                                        </div>
                                        <div class="form-card  m-0">
                                            <textarea asp-for="Review.Mesage" placeholder="Rəyiniz"></textarea>
                                            <span class="text-danger" asp-validation-for="Review.Mesage"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <button class="btn primary-button martop-30" type="submit">
                                           Rəy yaz
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                           
                        }



                    </div>
                </div>
                <div class="col-xl-3 col-lg-4  ">
                    <div class="sidebar-right margin-right-20">
                        <!-- Sidebar search item start-->
                        @*<div class="sidebar-wrap">
                            <h3 class="sidebar-title">Search</h3>
                            <div class="search-widget sidebar-widget">
                                <form action="#">
                                    <input placeholder="Search" type="text">
                                    <button type="submit"><i class="fa fa-search"></i></button>
                                </form>
                            </div>
                        </div>*@
                        <!-- Sidebar search item end-->
                        <!-- Sidebar category item start -->
                        <div class="sidebar-wrap">
                            <h3 class="sidebar-title">Post Categories</h3>
                            <div class="category-post sidebar-widget">
                                <ul>

                                    <li>
                                        <a href="#" class="active m-0">
                                            <i class="fa fa-angle-right"></i> All
                                            <span>(65)</span>
                                        </a>
                                    </li>
                                    @foreach (var item in Model.Categories)
                                    {
                                        @if (item.Blogs.Count != 0)
                                        {
                                            <li>
                                                <a asp-controller="Blog" asp-action="Index" asp-route-id="@item.Id" class="">
                                                    <i class="fa fa-angle-right"></i> @item.Name
                                                    <span>(@item.Blogs.Count())</span>
                                                </a>
                                            </li>
                                            }
                                        }




                                    </ul>
                            </div>
                        </div>
                        <!-- Sidebar resent post item -->
                        <div class="sidebar-wrap">
                            <h3 class="sidebar-title">Recent Post</h3>

                            <div class="recent-post-widget sidebar-widget">
                                @foreach (var item in Model.Blogs)
                                {
                                    <div class="recent-post d-flex">
                                        <div class="post-img">
                                            <a href="blog-details"><img src="~/Uploads/@item.Image" alt=""></a>
                                        </div>
                                        <div class="post-media">
                                            <span class="date">@item.AddedDate.ToString("dd MMM yyyy")</span>
                                            <h5>
                                                <a asp-controller="blog" asp-action="details" asp-route-id="@item.Id">
                                                   @item.Title.Substring(0,20)
                                                </a>
                                            </h5>
                                        </div>
                                    </div>
                                }
                              
                            </div>
                        </div>
                        <!-- Sidebar tag item  start-->
                        <div class="sidebar-wrap">
                            <h3 class="sidebar-title">Popular Tag</h3>

                            <div class="sidebar-tag sidebar-widget d-inline-block">
                                <ul>
                                    <li><a href="#">Fashion</a></li>
                                    <li><a href="#">Organic</a></li>
                                    <li><a href="#">Old Fashion</a></li>
                                    <li><a href="#">Men</a></li>
                                    <li><a href="#">Fashion</a></li>
                                    <li><a href="#">Dress</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- Sidebar banner item -->
                        <div class="sidebar-wrap-image sidebar-wrap p-0 mb-0">
                            <div class="banner-mini-card">
                                <div class="banner-img">
                                    <img src="~/assets/images/banner/3.jpg" alt="">
                                </div>
                                <div class="banner-content">
                                    <span class="category">Best Seller</span>
                                    <h6 class="title">
                                        Flower Vase <br>
                                        &amp; Poot
                                    </h6>
                                    <a href="#" class=" btn primary-button text-uppercase">
                                        Shop
                                        Now
                                    </a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--Blog details section end-->
</main>

Mioca/Mioca/Views/Blog/Index.cshtml
@model BlogVm
@inject SignInManager<User> SignInManager
@{
    ViewData["Title"] = "Blog";
}

<main>
    <!--Breadcrumb section start-->
    <section class="breadcrumb-section">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-12 text-center">
                    <h1 class="page-name ">Blog</h1>
                    <nav class="d-flex justify-content-center" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Blog</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!--Breadcrumb section end-->
    <!--Blog section start-->
    <section class="section-style-one">
        <div class="container">
            <div class="row">

              <vc:blog></vc:blog>

                
            </div>
            <div class="pagination justify-content-center mt-0 mb-0">
                <div class="pages">
                    <ul>
                        @{
                            int j = 0;
                        }
                        @if (ViewBag.prewPage != 0)
                        {
                            <li class="page-item">
                                <a class="page-link" asp-controller="blog" asp-action="index" asp-all-route-data="@ViewBag.Filter" asp-route-page="@ViewBag.prewPage"><i class="fa fa-angle-left"></i></a>
                            </li>
                        }
                        @for (int i = 1; i <= ViewBag.PageCount; i++)
                        {
                            <li class="page-item"><a class="page-link @(ViewBag.ActivePage==i?"active":"")" asp-controller="blog" asp-action="index" asp-all-route-data="@ViewBag.Filter" asp-route-page="@i">@i</a></li>
                            j = i;
                        }
                        @if (ViewBag.nextPage <= j)
                        {
                            <li class="page-item">
                                <a class="page-link"  asp-controller="blog" asp-action="index" asp-all-route-data="@ViewBag.Filter" asp-route-page="@ViewBag.nextPage"><i class="fa fa-angle-right"></i></a>
                            </li>
                        }


                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!--Blog section end-->
</main>